# Configuration file.
# You can add any fields you need, be sure to update DropTokenConfiguration accordingly.
template: Hello
databaseName: droptoken
dbConnectionString: "mongodb://localhost:27018"
minPlayers: 2
minGridLength: 4

logging:
  level: INFO
  appenders:
    - type: console
      threshold: TRACE
      target: stderr